# -*- coding: utf-8 -*-
"""EDXL-agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLup80gq8rGi2Cfx34iViQgVj3zSM8T_
"""

import xml.etree.ElementTree as ET
from xml.dom import minidom
from datetime import datetime

def run_edxl_agent(input_data):
    """
    Takes the JSON/Dictionary output from Agents 1-4
    and converts it into a standardized EDXL-DE/RM XML string.
    """
    # 1. Create the Root Element: EDXLDistribution (The Envelope)
    root = ET.Element("EDXLDistribution", xmlns="urn:oasis:names:tc:emergency:EDXL:DE:1.0")

    # Generate dynamic metadata for the envelope
    # e.g., MSG-2026-06-26-1715
    current_time = datetime.now().strftime("%Y-%m-%d-%H%M")
    ET.SubElement(root, "distributionID").text = f"MSG-{current_time}"
    ET.SubElement(root, "senderID").text = "operations.disaster.management@gov.in"

    # Format current timestamp to ISO format with timezone placeholder
    ET.SubElement(root, "dateTimeSent").text = datetime.now().isoformat() + "+05:30"
    ET.SubElement(root, "distributionStatus").text = "Actual"
    ET.SubElement(root, "distributionType").text = "Report"

    # Keywords from Agent 1 & 2
    combined_keywords = ET.SubElement(root, "combinedKeywords")
    ET.SubElement(combined_keywords, "keyword").text = input_data.get("disaster_type", "Emergency")
    ET.SubElement(combined_keywords, "keyword").text = f"{input_data.get('severity', 'Unknown')} Severity"
    ET.SubElement(combined_keywords, "keyword").text = "Resource Allocation"

    # Target Recipients
    explicit_address = ET.SubElement(root, "explicitAddress")
    ET.SubElement(explicit_address, "explicitAddressScheme").text = "AgencyID"
    ET.SubElement(explicit_address, "explicitAddressValue").text = "NDRF_HQ, Local_Hospitals, Civil_Defense"

    # 2. Create Content Object (The actual letter inside)
    content_object = ET.SubElement(root, "contentObject")
    ET.SubElement(content_object, "contentDescription").text = f"Resource Deployment and Situation Report for {input_data.get('location', 'Unknown')} {input_data.get('disaster_type', 'Event')}"

    xml_content = ET.SubElement(content_object, "xmlContent")

    # Resource Message Payload
    resource_msg = ET.SubElement(xml_content, "ResourceMessage", xmlns="urn:oasis:names:tc:emergency:EDXL:RM:1.0")

    # Mapping Agent 1 & 2: Incident Information
    incident_info = ET.SubElement(resource_msg, "IncidentInformation")
    ET.SubElement(incident_info, "IncidentDescription").text = (
        f"{input_data.get('disaster_type')} incident in {input_data.get('location')} "
        f"triggered by {input_data.get('rainfall')}mm rainfall. Risk level: {input_data.get('risk_level')}."
    )
    ET.SubElement(incident_info, "IncidentLocation").text = input_data.get("location")
    ET.SubElement(incident_info, "Severity").text = input_data.get("severity")
    ET.SubElement(incident_info, "DamageScore").text = str(input_data.get("damage_score"))
    ET.SubElement(incident_info, "AffectedPopulation").text = str(input_data.get("affected_population"))

    # Mapping Agent 3: Resource Allocations
    resource_deployment = ET.SubElement(resource_msg, "ResourceDeployment")

    # List of resource keys to look for from Agent 3
    resources_to_map = {
        "rescue_teams": "Rescue Team",
        "ambulances": "Ambulance",
        "medical_units": "Medical Unit",
        "food_packets": "Food Packet"
    }

    for json_key, official_name in resources_to_map.items():
        if json_key in input_data:
            resource_node = ET.SubElement(resource_deployment, "Resource")
            ET.SubElement(resource_node, "Type").text = official_name
            ET.SubElement(resource_node, "Quantity").text = str(input_data[json_key])

    # Mapping Route Agent: Logistics Information
    logistics_info = ET.SubElement(resource_msg, "LogisticsInformation")
    evac_routes = ET.SubElement(logistics_info, "EvacuationRoutes")

    for route in input_data.get("evacuation_routes", []):
        ET.SubElement(evac_routes, "Route").text = route

    # 3. Pretty Print the XML so it looks clean and readable
    xml_str = ET.tostring(root, encoding="utf-8")
    parsed_str = minidom.parseString(xml_str)
    return parsed_str.toprettyxml(indent="    ")


# --- EXECUTING & TESTING THE AGENT ---
if __name__ == "__main__":
    # This is the exact sample payload from your team's previous agents
    sample_pipeline_input = {
        # Agent 1 Output
        "location": "Chennai",
        "disaster_type": "Flood",
        "rainfall": 120,
        "temperature": 29,
        "social_reports": 340,
        "emergency_calls": 120,

        # Agent 2 Output
        "severity": "Extreme",
        "affected_population": 50000,
        "damage_score": 92,
        "risk_level": "Critical",

        # Agent 3 Output
        "rescue_teams": 50,
        "ambulances": 10,
        "medical_units": 5,
        "food_packets": 50000,

        # Route Agent Output
        "evacuation_routes": ["Shelter A", "Shelter C"]
    }

    # Run your agent!
    edxl_xml_output = run_edxl_agent(sample_pipeline_input)

    # Print the result to the console
    print(edxl_xml_output)

    # Save it to a file so you can show your team
    with open("edxl_output.xml", "w", encoding="utf-8") as f:
        f.write(edxl_xml_output)
    print("\n Success! EDXL agent output saved to 'edxl_output.xml'")